import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "url";
import log from "./log.js";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const docsPagesPath = path.join(__dirname, "../../docs/");
const docsPath = path.join(__dirname, "../../docs.json");

export async function autogenerateDocs(client) {
  let docsConfig = JSON.parse(fs.readFileSync(docsPath, "utf8"));
  let sections = [];
  let newConfig = {};
  sections = Object.keys(client).filter((section) => {
    return client[section].length > 0;
  });
  let sidebar = [];
  sidebar = sections.map((section) => {
    return [
      section,
      [
        ...client[section].map((model) => {
          return [model.data.name, `/${section}/${model.data.name}`];
        }),
      ],
    ];
  });
  delete docsConfig.sidebar;
  newConfig = {
    ...docsConfig,
    sidebar,
  };
  fs.writeFileSync(docsPath, JSON.stringify(newConfig, null, 2));
  log("info", `Docs generated.`);
}
