import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "url";
import log from "./log.js";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const docsPagesPath = path.join(__dirname, "../../docs/");
const docsPath = path.join(__dirname, "../../docs.json");

export async function autogenerateDocs(client) {
  let docsConfig = JSON.parse(fs.readFileSync(docsPath, "utf8"));
  let sections = [];
  let newConfig = {};
  sections = Object.keys(client).filter((section) => {
    return client[section].length > 0;
  });
  let sidebar = [];
  sidebar = sections.map((section) => {
    return [
      `${section.charAt(0).toUpperCase() + section.slice(1)} Models`,
      [
        ...client[section].map((model) => {
          return [model.data.fullName, `/${section}/${model.data.name}`];
        }),
      ],
    ];
  });
  delete docsConfig.sidebar;
  newConfig = {
    ...docsConfig,
    sidebar,
  };
  fs.writeFileSync(docsPath, JSON.stringify(newConfig, null, 2));
  log("info", `Sidebar docs generated.`);
  for (let section of sections) {
    let folderExists = fs.existsSync(path.join(docsPagesPath, section));
    if (!folderExists) {
      fs.mkdirSync(path.join(docsPagesPath, section));
    }
    for (let model of client[section]) {
      let docsModelPath = path.join(
        docsPagesPath,
        section,
        `${model.data.name}/index.mdx`
      );
      let docsModelContent = `---\ntitle: ${model.data.fullName}\n---\n\n# ${model.data.fullName}\n\n## Parameters\n\n`;
      for (let parameter of Object.keys(model.data.parameters)) {
        docsModelContent += `\n- **${parameter}**\n  - Type: ${model.data.parameters[parameter].type}\n  - Required: ${model.data.parameters[parameter].required}\n`;
        if (model.data.parameters[parameter].options) {
          docsModelContent += `  - Options: ${model.data.parameters[
            parameter
          ].options.join(", ")}\n`;
        }
        if (model.data.parameters[parameter].default) {
          docsModelContent += `  - Default: ${model.data.parameters[parameter].default}\n`;
        }
      }
      docsModelContent += `\n## Examples\n\n`;
      if (!fs.existsSync(path.join(docsPagesPath, section, model.data.name))) {
        fs.mkdirSync(path.join(docsPagesPath, section, model.data.name));
      }
      fs.writeFileSync(docsModelPath, docsModelContent);
    }
  }
}
