import { autogenerateDocs } from "./utils/docs.js";
import textHandler from "./handlers/text.js";
import imageHandler from "./handlers/image.js";
import audioHandler from "./handlers/audio.js";
import log from "./utils/log.js";
import videoHandler from "./handlers/video.js";
const client = {
  text: [],
  image: [],
  audio: [],
  video: [],
};
import "dotenv/config";

(async () => {
  await textHandler(client);
  await imageHandler(client);
  await audioHandler(client);
  await videoHandler(client);
  await autogenerateDocs(client);
})();
